###### THIS IS A BLANK CONFIG ######
# Editing this file is useless
# You have to move it to config.yaml
####################################

Token : "INSERT HERE THE DISCORD BOT TOKEN"
GoogleApiKey : "INSERT HERE YOUR YOUTUBE API KEY" 

Status : "!Help ğŸ˜‰"

Prefix : "!"

URL : "https://omega-numworks.github.io/"

ForbiddenWords:
  - "slt"
  - "salut"
  - "bonjour"
  - "bonsoir"

ForbiddenWordsResponseFR: "dans les channels ne terminant pas par `-fr`, il est impÃ©ratif d'Ã©crire en anglais, Ã©tant donnÃ© que nous avons des contributeurs anglais. Si vous souhaitez parler en franÃ§ais, d'autres channels sont disponibles sur notre serveur. Plus d'infos sur <#663457765058150400>."
ForbiddenWordsResponseEN: "in channels not ending with `-fr`, it is imperative to write in English, since we have English contributors. If you wish to speak in French, other channels are available on our server. More info on <#663457765058150400>."

ShortForbiddenWords:
  - "mdr"

ShortForbiddenWordsResponse : "in english please!"

Commands :
  help :
    input : "help"
    description : "Return a help"
  team :
    input : "team"
    description : "Return infos about the omega team"
    file : "team.json"
  repository:
    input : "repositories"
    description : "Return the list of the repositories in the Omega project"
    repository :
      - url : "https://github.com/Omega-Numworks/Omega"
        name : "Omega"
        desc : "Omega main repository"
      - url : "https://github.com/Omega-Numworks/Omega-Themes"
        name : "Omega themes"
        desc : "Omega themes desc"
      - url : "https://github.com/Omega-Numworks/Omega-CLI-Installer"
        name : "Omega cli installer"
        desc : "Omega cli installer desc"
      - url : "https://github.com/Omega-Numworks/Omega-Design"
        name : "Omega Design"
        desc : "Omega design desc"
  play :
    input : "play"
    description : "Requiers the song Url ğŸ“ or name and Connect me to your vocal channel if I wasn't allredy connect, else add your song to the queue !"
  stop :
    input : "stop"
    description : "â¹ Stop the music playing ğŸ¶!"
  pause :
    input : "pause"
    description : "â¸ Put music in pause ğŸ¶!"
  resume :
    input : "resume"
    description : "â–¶ Resume paused music ğŸ¶!"
  skip :
    input : "skip"
    description : "â­ Skip the current song ğŸ¶!"
  nowplaying :
    input : "np"
    description : "Return the current playing song ğŸ¶!"
  queue : 
    input : "queue"
    description : "Return the list of queued map ğŸ¶!"
  volume :
    input : "volume"
    description : "Returne my volume level ğŸ”‰, with the number argument you can deacrease my volume or increase my volume."